"""Reconstructed synthetic room. Regenerated bytes, not original benchmark inputs."""
import bpy,json
from pathlib import Path
from mathutils import Vector
O=Path(__file__).parent/'assets';O.mkdir(exist_ok=True)
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
s=bpy.context.scene;s.render.engine='CYCLES';s.cycles.samples=64;s.cycles.use_denoising=False;s.world.color=(.3,.3,.3);s.view_settings.view_transform='AgX'
M={};objects=[]
for n,c in [('wall',(.72,.72,.67)),('wood',(.32,.13,.055)),('floor',(.43,.27,.13)),('sofa',(.09,.25,.34)),('cushion',(.66,.38,.13)),('rug',(.56,.51,.38)),('black',(.012,.018,.023)),('metal',(.09,.095,.1)),('white',(.8,.8,.75))]:
 m=bpy.data.materials.new(n);m.diffuse_color=(*c,1);m.use_nodes=True;p=m.node_tree.nodes.get('Principled BSDF');p.inputs['Base Color'].default_value=(*c,1);p.inputs['Roughness'].default_value=.65;M[n]=m
def pos(v):return(v[0],-v[2],v[1])
def cube(n,c,d,ma,idx=0,bevel=.02):
 bpy.ops.mesh.primitive_cube_add(size=1,location=pos(c));o=bpy.context.object;o.name=n;o.dimensions=(d[0],d[2],d[1]);bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o.data.materials.append(M[ma]);o.pass_index=idx
 if bevel:
  mod=o.modifiers.new('soft_edges','BEVEL');mod.width=bevel;mod.segments=3;o.modifiers.new('weighted_normals','WEIGHTED_NORMAL')
 return o
def semantic(n,category,c,d):
 i=len(objects)+1;objects.append(dict(id=n,category=category,center=dict(zip('xyz',c)),dimensions=dict(zip('xyz',d)),transform=[[1,0,0,c[0]],[0,1,0,c[1]],[0,0,1,c[2]],[0,0,0,1]],confidence='high',instance_index=i));return i
cube('floor',(0,-.075,0),(6,.15,5),'floor',bevel=0)
for n,c,d in [('rear',(0,1.4,-2.55),(6.1,2.8,.1)),('left',(-3.05,1.4,0),(.1,2.8,5)),('right',(3.05,1.4,0),(.1,2.8,5))]:cube('wall_'+n,c,d,'wall',bevel=0)
for x in range(-6,7):cube('plank_seam',(x*.46,.003,0),(.008,.005,5),'wood',bevel=0)
for z in [-2,-.5,1]:
 for x in range(-6,6):cube('plank_end',(x*.46+.23,.004,z+(x%2)*.5),(.46,.004,.007),'wood',bevel=0)
cube('rug',(0,.015,-.1),(3.5,.025,2.9),'rug')
i=semantic('sofa','sofa',(-1.05,.48,-1.75),(2.4,.96,1));cube('sofa_base',(-1.05,.32,-1.75),(2.4,.44,1),'sofa',i,.08);cube('sofa_back',(-1.05,.73,-2.12),(2.4,.52,.23),'sofa',i,.09)
for x in [-2.18,.08]:cube('sofa_arm',(x,.56,-1.75),(.22,.62,1),'sofa',i,.08)
for x in [-1.62,-.49]:cube('seat_cushion',(x,.56,-1.67),(1.05,.15,.7),'sofa',i,.07);cube('throw_pillow',(x,.77,-1.94),(.47,.4,.16),'cushion',i,.07)
i=semantic('coffee_table','table',(-.8,.27,-.15),(1.4,.54,.75));cube('table_top',(-.8,.51,-.15),(1.4,.06,.75),'wood',i)
for x in [-1.4,-.2]:
 for z in [-.44,.14]:cube('table_leg',(x,.25,z),(.055,.5,.055),'black',i)
for j in range(3):cube('book',(-.9+j*.025,.57+j*.04,-.1),(.35,.035,.24),'cushion' if j%2 else 'white',i,.004)
i=semantic('dining_table','table',(1.85,.4,.3),(1.35,.8,1.1));cube('dining_top',(1.85,.76,.3),(1.35,.08,1.1),'wood',i)
for x in [1.3,2.4]:
 for z in [-.1,.7]:cube('dining_leg',(x,.36,z),(.08,.72,.08),'wood',i)
for x,z in [(1.85,1.2),(1.85,-.65)]:
 i=semantic('chair_'+str(len(objects)),'chair',(x,.48,z),(.55,.96,.6));cube('chair_seat',(x,.45,z),(.55,.08,.55),'wood',i);cube('chair_back',(x,.73,z+(.24 if z>0 else -.24)),(.55,.5,.07),'wood',i)
 for xx in [x-.21,x+.21]:
  for zz in [z-.21,z+.21]:cube('chair_leg',(xx,.21,zz),(.05,.42,.05),'wood',i)
i=semantic('cabinet','storage',(1.75,.5,-2.15),(1.6,1,.55));cube('cabinet',(1.75,.5,-2.15),(1.6,1,.55),'white',i)
for x in [1.37,2.13]:cube('cabinet_door',(x,.5,-1.865),(.74,.9,.025),'wood',i);cube('handle',(x,.62,-1.835),(.025,.16,.03),'metal',i)
i=semantic('television','television',(-2.88,1.25,.1),(.12,.9,1.5));cube('tv_frame',(-2.88,1.25,.1),(.12,.9,1.5),'black',i);cube('tv_screen',(-2.81,1.25,.1),(.008,.78,1.36),'metal',i)
for x,w,h in [(-1.7,.6,.65),(-.85,.55,.8),(.05,.5,.6)]:
 cube('art_frame',(x,1.85,-2.47),(w,h,.04),'wood');cube('art_canvas',(x,1.85,-2.44),(w-.07,h-.07,.02),'white')
 for q in range(6):cube('art_shape',(x-w*.3+q*w*.12,1.85+(q%3-1)*.13,-2.425),(.04,.1+(q%2)*.13,.008),'sofa' if q%2 else 'cushion')
i=semantic('floor_lamp','lamp',(.5,.9,-1.9),(.42,1.8,.42));cube('lamp_base',(.5,.035,-1.9),(.35,.07,.35),'black',i);cube('lamp_stem',(.5,.82,-1.9),(.035,1.6,.035),'black',i)
bpy.ops.mesh.primitive_cone_add(vertices=32,radius1=.23,radius2=.14,depth=.3,location=pos((.5,1.65,-1.9)));o=bpy.context.object;o.name='lamp_shade';o.data.materials.append(M['white']);o.pass_index=i
for loc,power,size in [((0,2.65,.4),450,4),((-2,2.4,1.8),300,2),((2,2.4,-1),200,2)]:
 bpy.ops.object.light_add(type='AREA',location=pos(loc));o=bpy.context.object;o.data.energy=power;o.data.shape='DISK';o.data.size=size
bpy.ops.object.camera_add();c=bpy.context.object;s.camera=c;c.name='camera';c.data.lens=24;c.data.sensor_width=36;c.data.sensor_fit='HORIZONTAL';c.data.clip_start=.05;c.data.clip_end=100
c.location=pos((-.9,1.65,2.25));c.rotation_euler=(Vector(pos((.1,.85,-1)))-c.location).to_track_quat('-Z','Y').to_euler();bpy.context.view_layer.update()
s.render.resolution_x=480;s.render.resolution_y=360;s.render.resolution_percentage=100;s.render.image_settings.file_format='JPEG';s.render.image_settings.quality=92;s.render.filepath=str(O/'room_preview.jpg');bpy.ops.render.render(write_still=True)
meshes=[]
for ob in s.objects:
 if ob.type!='MESH':continue
 e=ob.evaluated_get(bpy.context.evaluated_depsgraph_get());m=e.to_mesh();points=[]
 for v in m.vertices:
  p=ob.matrix_world@v.co;points.append([p.x,p.z,-p.y])
 meshes.append(dict(name=ob.name,points=points,counts=[len(f.vertices) for f in m.polygons],indices=[i for f in m.polygons for i in f.vertices],color=list(ob.data.materials[0].diffuse_color)[:3]));e.to_mesh_clear()
(O/'meshes.json').write_text(json.dumps(meshes));(O/'semantic_objects.json').write_text(json.dumps(dict(regenerated=True,not_original_benchmark_bytes=True,units='meters',up_axis='Y',objects=objects),indent=2));bpy.ops.wm.save_as_mainfile(filepath=str(O/'room.blend'))
s.render.resolution_x=960;s.render.resolution_y=720;s.render.image_settings.file_format='PNG';s.render.filepath=str(O/'room_camera.png');bpy.ops.render.render(write_still=True)
c.location=(8,-9,7);c.rotation_euler=(Vector((0,0,.6))-c.location).to_track_quat('-Z','Y').to_euler();c.data.type='ORTHO';c.data.ortho_scale=9;bpy.data.objects['wall_left'].hide_render=True;bpy.data.objects['wall_right'].hide_render=True;s.render.filepath=str(O/'room_overview.png');bpy.ops.render.render(write_still=True)

